services:
  # Use postgres/example user/password credentials
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"

    

  api-picpay-simplificado:
    build: .
    container_name: picpay-simplificado
    ports:
      - "${HTTP_PORT:-3000}:3000"
      - "${HTTPS_PORT:-3050}:3050"
    restart: "always"
    environment:
      - USE_HTTPS=${USE_HTTPS}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
    env_file:
    - .env

  